### ISSUE TITLE
Share buttons

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs-site#34]
I think it would be good, for obvious reasons, to add some share buttons to blog posts.

**Comment by leggetter** [comment]
This is a good idea. Is there a really simple solution for this?

We just need to add the buttons here: https://github.com/BladeRunnerJS/brjs-site/blob/gh-pages/_layouts/post.html

The code we need to add is:

```
<!--twitter-->
          <a href="https://twitter.com/share" class="twitter-share-button" data-text="{{ page.title }}">Tweet</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
          <!--twitter-->

          <!--plus-->
          <div class="g-plusone" data-size="medium"></div>
          <script type="text/javascript">
            (function() {
              var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
              po.src = 'https://apis.google.com/js/platform.js';
              var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
            })();
          </script>
          <!--plus-->
```

Fancy a stab at putting it somewhere that doesn't look out of place? ;)

**Comment by janhancic** [comment]
Sure, I'll have a stab at it. If I can first get the site running locally :)

**Comment by leggetter** [comment]
https://github.com/BladeRunnerJS/brjs-site#running-the-website

If you're on something other than Mac, would be really great to get some instructions for your environment. Also, any gotchas. I'll help if I can. Thanks, Jan!

**Comment by janhancic** [comment]
I'm on a mac, got it running, it just took some time for the `gem install` to start showing any output and I thought it's not working. All good now.

Should I be basing my changes on `master` or `develop`?

**Comment by janhancic** [comment]
Ah, `gh-pages`, correct?

**Comment by leggetter** [comment]
yeah, gh-pages is the live site. So, branch from there. develop contains the details for the upcoming v0.4 release.

**Comment by janhancic** [comment]
Opened pull request #35 
Closing this.
