### ISSUE TITLE
[Discuss] Outline for BRJS Getting Started Guide

### ISSUE THREAD

**Issue by leggetter** [BladeRunnerJS/brjs-site#4]
## Create an Application
- Use the CLI to create an application
- State what this created; default aspect, blade etc.
## Develop a Blade
- View the code for the Blade
- Run the Blade in a Workbench
- Edit the Blade code and see the change in the workbench
- Run the Blade within the application
## Create a second Blade
- Demonstrate interacting with a Blade via EventHub in a Workbench (_do we have a Workbench Tool for this?_)
- Demonstrate communication between the blades via the EventHub
## Create a service
- Do in-memory persistence, stating that it could be swapped out for real persistence or LocalStorage
## Tests
- Write a very simple test and demonstrate how it can be run.
## Build and Deploy
- Simple deploy to local Tomcat. Note that flat-file deploy is a priority.
## Where next?
- Link to other relevant content; probably just the docs for now.

**Comment by fauna5** [comment]
Hey phil. Maybe i can pick this up? I'm taking wednesday to try BRJS. This would be a good exercise to try it out with.
