### ISSUE TITLE
br.event-hub missing?

### ISSUE THREAD

**Issue by mcaine** [BladeRunnerJS/brjs-site#40]
I am working through the getting started tutorial, and I am getting an error

Uncaught Error: InvalidParametersError: br/ServiceRegistry could not locate a service for: br.event-hub
    at Object.getService (http://localhost:7070/brjs-mike-todo/todo-bladeset/blades/todoinput/workbench/js/js.bundle:59009:10)
    at new ExamplePresentationModel (http://localhost:7070/brjs-mike-todo/todo-bladeset/blades/todoinput/workbench/js/js.bundle:79866:37)
    at initialize (http://localhost:7070/brjs-mike-todo/todo-bladeset/blades/todoinput/workbench/:18:17)
    at onload (http://localhost:7070/brjs-mike-todo/todo-bladeset/blades/todoinput/workbench/:27:115) js.bundle:59009

The tutorial claims that br.event-hub is a default service, yet I can't find where it is defined. Has this been renamed or removed?

**Comment by leggetter** [comment]
It looks like an update to the docs has gone live before it's meant to. If you're using v0.3 then the service name is `br.demo-event-hub`. I've reverted the Getting Started docs to reflect this.

I'm just trying out v0.3 against the guide to make sure nothing else has been prematurely pushed. Hopefully this gets you past this problem. Please do submit additional issues if you find any other problems.

FYI v0.4 should represent a significant improvement, mainly in terms of how it will allow you to focus on writing functionality and not adding boilerplate closures to work around the browser runtime. The toolkit handles that for you. More information available in the [Write BRJS apps using NodeJS style code blog post](http://bladerunnerjs.org/blog/bladerunnerjs-sprint-4/).

**Comment by mcaine** [comment]
Thanks for the quick reply!

**Comment by leggetter** [comment]
v0.3 runs fine against the version in master in brjs-todo https://github.com/BladeRunnerJS/brjs-todo. I've also looked through the guide and I can't see anything else out of place.

Sorry about that hiccup and thanks very much for trying out this pre-release. Great to have you on the cutting edge!
