### ISSUE TITLE
[QUESTION] Django Integration

### ISSUE THREAD

**Issue by volkovasystems** [BladeRunnerJS/brjs-site#48]
Is it feasible to integrate Django and BladeRunnerJS?

**Comment by leggetter** [comment]
@volkovasystems - sorry for the delay.

Integration can take two forms:
1. If you are building API endpoints in Django then you would create a JavaScript [service](http://bladerunnerjs.org/docs/concepts/services/) object that interacts with that endpoint. That service is then fetched by functionality within your front-end via the [ServiceRegistry](http://bladerunnerjs.org/docs/concepts/service_registry/).
2. If you want to integrate Blades into an existing app then we don't have a full solution for that yet. You could create your Blades and then deploy as flat file (pending feature). Then include the deployed assets in your existing app and write some code to integrate the Blade.

Point 1. introduces a couple of concepts. 2. isn't something we've a fully thought-out solution right now. So, if something needs clarified, please just ask.
