### ISSUE TITLE
Submit to HN

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/brjs-site#5]
Hey guys,

if you are planning on submitting BR, once it's released, to Hacker News I would suggest you study this first:

http://nathanael.hevenet.com/the-best-time-to-post-on-hacker-news-a-comprehensive-answer/
http://hnpickup.appspot.com/

This will tell you when the best time to submit is (i.e. best time that the story will actually got picked up).

And if you do submit, please let me know in advance so I can give a up-vote. I have some [karma-juice](https://news.ycombinator.com/user?id=CWIZO) which should help a bit hopefully :)

**Comment by leggetter** [comment]
Clearly we've hit HN :)
