### ISSUE TITLE
GwtTestRunner can't handle '=' in the value of an acceptance test assertion

### ISSUE THREAD

**Issue by tobycatlin** [BladeRunnerJS/brjs-site#82]
When writing acceptance tests, it's not possible to use an '=' in the value of an assertion.
E.g.

```
it("binds the currency displayed to the instrument", function()
{
 given("ticket.viewOpened = true");
 when("ticket.model.ticketHeader.currencyPair => 'USDGBP'");
 then("ticket.view.(.execute-container .dealt-currency).text = 'USD='");
});
```

will give an error along the lines of:
`binds the currency displayed to the instrument failed (237,00 ms): InvalidPropertyValueError: InvalidPropertyValueError: Error handling statement 'ticket.view.(.execute-container .dealt-currency).text = 'USD='': 'null' is not a valid type (only strings, numbers, booleans and undefined are supported)`

This is because of the regex used in GwtTestRunner (line 495) to parse the statement:
`/(.+)(\=\>|\=)(.+)/i`
A simple fix seems to be to enforce a space around the operator, so that the regex reads:
`/(.+)( \=\>|\= )(.+)/i`

internal URL for this issue - http://yourls.caplin.com/5

**Comment by andy-berry-dev** [comment]
This should have been raised against BRJS - see https://github.com/BladeRunnerJS/brjs/issues/1008 for the issue.
